Update 2.2.2
AnacondaRecipes/werkzeug-feedstock pull request #6
Opened 2022-10-31 20:41 UTC by SC426

2022-10-31 20:42 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

ERROR: /tmp/abs_98fm0i2_b5/clone/recipe/meta.yaml:23: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
ERROR: /tmp/abs_98fm0i2_b5/clone/recipe/meta.yaml:24: remove_python_pinning: On arch specific packages, python deps should not be constrained.
WARNING: /tmp/abs_98fm0i2_b5/clone/recipe/meta.yaml:44: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_98fm0i2_b5/clone/recipe/meta.yaml:44: missing_doc_source_url: The recipe is missing a doc_source_url
Errors were found

2022-11-10 20:00 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_378_z_r68z/clone/recipe/meta.yaml:45: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_378_z_r68z/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-11 09:21 UTC, katietz requested changes
ok, with those 2 changes

2022-11-11 09:21 UTC, katietz commented on abs.yaml
> +channels:
please remove this channel part from abs.yaml

2022-11-11 09:21 UTC, katietz commented on recipe/meta.yaml
> +  skip: True #[py<37]
please add a space before, and one after the '#'. Selectors should have the pattern '  # [<selector-condition>]'

2022-11-11 21:02 UTC, varlackc reviewed
As soon as we fix the issue with the skip we should be good to approve the package.

2022-11-11 21:24 UTC, marcoesters commented on abs.yaml
> +channels:
The channel part is important for now because it is part of a dependency chain. The file will be removed before merging.

2022-11-15 16:45 UTC, SC426 commented
> As soon as we fix the issue with the skip we should be good to approve the package.

2022-11-15 16:45 UTC, SC426 commented on recipe/meta.yaml
> +  skip: True #[py<37]
This has been fixed

2022-11-15 17:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_fd2f23unp1/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_fd2f23unp1/clone/recipe/meta.yaml:45: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-11-17 08:31 UTC, skupr-anaconda approved these changes

2022-11-17 18:15 UTC, SC426 commented
> As soon as we fix the issue with the skip we should be good to approve the package.

This has been fixed.

2022-12-02 17:20 UTC, marcoesters approved these changes
LGTM

Wait until all packages that depend on werkzeug have been updated before merging though. We have to merge/upload this concurrently with `flask` and `airflow`

2022-12-16 18:32 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_f5anq3qgao/clone/recipe/meta.yaml:45: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_f5anq3qgao/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-16 18:39 UTC, merged

2022-12-16 18:39 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_e8bn6_hmof/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_e8bn6_hmof/clone/recipe/meta.yaml:45: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>